/**
 * Common builds and sources relevant to all Fabric modules. Based in 1.16.5
 */
buildscript {
    repositories {
        gradlePluginPortal() {
            content {
                plugin_portal_content.split(';').each {grp ->
                    includeGroup grp
                }
            }
        }
        maven {
            name = 'Fabric'
            url = uri 'https://maven.fabricmc.net/'
            content {
                fabric_content.split(';').each {grp ->
                    includeGroup grp
                }
            }
        }
    }
    dependencies {
        classpath "$loom_plugin:$loom_version"
    }
}

apply from: rootProject.file('gradle\\java8-module.gradle')
apply from: rootProject.file('gradle\\fabric.gradle')

plugins.apply 'fabric-loom'

def base = project ':api'

configurations {
    dev {
        canBeResolved = false
        canBeConsumed = true
    }
}

dependencies {
    minecraft "$fabric_mc:$minecraft_1_16_5"
    mappings loom.layered() {
        officialMojangMappings()
        parchment "$parchment_data-$minecraft_1_16_5:$parchment_1_16_5@zip"
    }

    compileOnlyApi base

    modImplementation "$fabric_loader_artifact:$fabric_loader"
    modImplementation "$fabric_api_artifact:$fabric_1_16_5"
    modImplementation "$til_artifact:$til_version"
}

processResources {
    from base.processResources.outputs
}

processTestResources {
    from base.processTestResources.outputs
}

jar {
    setArchiveBaseName mod_id
    from(base.jar.archiveFile.collect { zipTree it })
}

artifacts {
    dev jar
}

tasks.compileJava.mustRunAfter ':api:build'