buildscript {
    repositories {
        gradlePluginPortal() {
            content {
                [ 'com.fasterxml.woodstox', 'com.fasterxml.jackson.core', 'com.fasterxml.jackson', 'com.fasterxml',
                  'com.google.code.findbugs', 'com.google.code.gson', 'com.google.errorprone', 'com.google.guava',
                  'com.google.j2objc', 'commons-io', 'io.fabric8', 'io.github.goooler.shadow', 'io.netty',
                  'jakarta.platform', 'me.jamiemansfield', 'org.apache', 'org.apache.ant', 'org.apache.commons',
                  'org.apache.logging', 'org.apache.logging.log4j', 'org.apache.maven', 'org.benf', 'org.cadixdev',
                  'org.checkerframework', 'org.codehaus.groovy', 'org.codehaus.plexus', 'org.codehaus.woodstox',
                  'org.eclipse.ee4j', 'org.eclipse.jdt', 'org.eclipse.jetty', 'org.eclipse.platform', 'org.jdom',
                  'org.jetbrains', 'org.jetbrains.kotlin', 'org.jetbrains.kotlinx', 'org.junit', 'org.mockito',
                  'org.ow2', 'org.ow2.asm', 'org.slf4j', 'org.sonatype.oss', 'org.springframework', 'org.vafer',
                  'org.zeroturnaround'].forEach { includeGroup it }
            }
        }
        maven {
            name = 'Fabric'
            url = uri 'https://maven.fabricmc.net/'
            content {
                [ 'fabric-loom', 'net.fabricmc', 'net.fabricmc.fabric-api' ].forEach { includeGroup it }
            }
        }
    }
    dependencies {
        classpath "$loom_plugin:$loom_version"
    }
}

apply from: rootProject.file('gradle\\java17-module.gradle')
apply from: rootProject.file('gradle\\fabric.gradle')

plugins.apply 'fabric-loom'

def base = project ':api'
def fabric = project ':fabric'
def shared = project ':shared:shared_1.19'

configurations {
    dev {
        canBeResolved = false
        canBeConsumed = true
    }
}

repositories {
    maven {
        name 'Modrinth'
        url = uri 'https://api.modrinth.com/maven'
        content {
            includeGroup 'maven.modrinth'
        }
    }
}

dependencies {
    minecraft "$fabric_mc:$minecraft_1_19_2"
    mappings loom.layered() {
        officialMojangMappings()
        parchment "$parchment_data-$minecraft_1_19_2:$parchment_1_19_2@zip"
    }

    compileOnlyApi base
    api project(path: ':fabric', configuration: 'dev')
    compileOnlyApi project(path: ':shared:shared_1.19', configuration: 'dev')

    modImplementation "$fabric_loader_artifact:$fabric_loader"
    modImplementation "$fabric_api_artifact:$fabric_1_19_2"
}

processResources {
    from fabric.processResources.outputs
}

processTestResources {
    from fabric.processTestResources.outputs
}

compileJava {
    source fabric.sourceSets.main.allJava
}

compileTestJava {
    source fabric.sourceSets.test.allJava
}

jar {
    setArchiveBaseName mod_id
    from(fabric.jar.archiveFile.collect { zipTree it })
}

artifacts {
    dev jar
}

tasks.compileJava.mustRunAfter ':fabric:build'
tasks.compileJava.mustRunAfter ':shared:shared_1.19:build'