/**
 * Build workflow guidelines
 * api -> (fabric, forge, legacy, neoforge) -> (1.12, 1.16, 1.18, 1.19, 1.20, 1.21) -> (minor versions) -> main
 * Shading and relocation must happen within each module to properly respect reobfuscation.
 * Any necessary reobfuscations must happen in the version the deobfuscations happened in.
 */
buildscript {
    repositories {
        gradlePluginPortal() {
            content {
                plugin_portal_content_short.split(';').each {grp ->
                    includeGroup grp
                }
            }
        }
    }
    dependencies {
        classpath "$wiki_plugin:$wiki_version"
    }
}

apply from: rootProject.file('gradle\\java23.gradle')
plugins.apply 'org.moddedmc.wiki.toolkit'

//noinspection GroovyUnusedAssignment
def base = project ':api'
def fabric = project ':fabric'
def legacy_1_12_2 = project ':legacy:1.12'
def fabric_1_16_5 = project ':fabric:fabric_1.16'
def forge_1_16_5 = project ':forge:forge_1.16'
def fabric_1_18_2 = project ':fabric:fabric_1.18'
def forge_1_18_2 = project ':forge:forge_1.18'
def shared_1_19_2 = project ':shared:shared_1.19:shared_1.19.2'
def shared_1_19_4 = project ':shared:shared_1.19:shared_1.19.4'
def shared_1_20_1 = project ':shared:shared_1.20:shared_1.20.1'
def shared_1_20_4 = project ':shared:shared_1.20:shared_1.20.4'
def shared_1_20_6 = project ':shared:shared_1.20:shared_1.20.6'
def shared_1_21_1 = project ':shared:shared_1.21:shared_1.21.1'

processResources {
    fabric.afterEvaluate {
        from it.processResources.outputs
    }
}

processTestResources {
    fabric.afterEvaluate {
        from it.processTestResources.outputs
    }
}

jar {
    legacy_1_12_2.afterEvaluate { from(it.shadowJar.archiveFile.collect { zipTree it }) }
    fabric_1_16_5.afterEvaluate { from(it.remapJar.archiveFile.collect { zipTree it }) }
    forge_1_16_5.afterEvaluate { from(it.shadowJar.archiveFile.collect { zipTree it }) }
    fabric_1_18_2.afterEvaluate { from(it.remapJar.archiveFile.collect { zipTree it }) }
    forge_1_18_2.afterEvaluate { from(it.shadowJar.archiveFile.collect { zipTree it }) }
    shared_1_19_2.afterEvaluate { from(it.sourceSets.main.output.classesDirs.asFileTree) }
    shared_1_19_4.afterEvaluate { from(it.sourceSets.main.output.classesDirs.asFileTree) }
    shared_1_20_1.afterEvaluate { from(it.sourceSets.main.output.classesDirs.asFileTree) }
    shared_1_20_4.afterEvaluate { from(it.sourceSets.main.output.classesDirs.asFileTree) }
    shared_1_20_6.afterEvaluate { from(it.sourceSets.main.output.classesDirs.asFileTree) }
    shared_1_21_1.afterEvaluate { from(it.sourceSets.main.output.classesDirs.asFileTree) }
    manifest {
        def versionStr = project.version.toString()
        def manifest_version = versionStr.contains('+') ?
                versionStr.substring(0,versionStr.indexOf('+')) : versionStr
        attributes([
                'Implementation-Title': project.name,
                'Implementation-Version': manifest_version,
                'TILMultiversionCoreMods': coremod_entrypoint,
                'TILMultiversionMods': mod_entrypoint
        ])
    }
}

[ ':legacy:1.12:build',
  ':fabric:fabric_1.16:build', ':forge:forge_1.16:build',
  ':fabric:fabric_1.18:build', ':forge:forge_1.18:build',
  ':shared:shared_1.19:shared_1.19.2:build',
  ':shared:shared_1.19:shared_1.19.4:build',
  ':shared:shared_1.20:shared_1.20.1:build',
  ':shared:shared_1.20:shared_1.20.4:build',
  ':shared:shared_1.20:shared_1.20.6:build',
  ':shared:shared_1.21:shared_1.21.1:build'
].forEach { tasks.jar.mustRunAfter it }

wiki {
    wikiAccessToken = wiki_token
    docs {
        mod_id {
            root = file "docs/$mod_id"
        }
    }
}