/**
 * All of the code is in the api project.
 * The legacy & 1.12.2 projects are only used for testing purposes
 */
buildscript {
    repositories {
        gradlePluginPortal() {
            content {
                plugin_portal_content_short.split(';').each {grp ->
                    includeGroup grp
                }
            }
        }
    }
    dependencies {
        classpath "$modrinth_plugin:$modrinth_version"
        classpath "$wiki_plugin:$wiki_version"
    }
}

apply from: rootProject.file('gradle\\java24.gradle')
plugins.apply 'com.modrinth.minotaur'
plugins.apply 'org.moddedmc.wiki.toolkit'

makeChangelogFile()

//noinspection GroovyUnusedAssignment
def base = project ':api'
def legacy_1_12_2 = project ':legacy:1.12'

jar {
    legacy_1_12_2.afterEvaluate {
        from(it.shadowJar.archiveFile.collect {
            zipTree it
        })
    }
    manifest {
        def ver_str = mod_version.toString()
        def manifest_version = ver_str.contains('+') ? ver_str.substring(0,ver_str.indexOf('+')) : ver_str
        attributes([
                'Implementation-Title': mod_name,
                'Implementation-Version': manifest_version,
                'TILMultiversionCoreMods': coremod_entrypoint,
                'TILMultiversionMods': mod_entrypoint
        ])
    }
}

tasks.jar.mustRunAfter ':legacy:1.12:build'

def makeChangelogFile() {
    def changelogFile = file "changelogs/${mod_version}.txt"
    if(!changelogFile.exists()) {
        def parent = changelogFile.parentFile
        if(!parent.exists()) parent.mkdirs()
        if(changelogFile.createNewFile()) {
            changelogFile.write '- WIP'
            logger.info "Created changelog file for new version at ${changelogFile.absolutePath}"
        } else logger.error "Failed to create changelog file for new version at ${changelogFile.absolutePath}"
    }
}

String readChangelog() {
    def changelogFile = file "changelogs/${mod_version}.txt"
    try {
        def lines = changelogFile.readLines()
        def builder = new StringBuilder()
        for(def line : lines) builder.append(line).append '\n'
        return builder.toString()
    } catch(Exception ex) {
        getLogger().error "Failed to read lines from $changelogFile", ex
    }
    return ""
}

List<String> readVersions() {
    return List.of(supported_versions.split(';')).stream().map(it -> "1.$it".toString()).toList()
}

modrinth {
    changelog = readChangelog()
    gameVersions = readVersions()
    loaders = [ 'forge', 'neoforge' ]
    projectId = 'music-triggers'
    token = modrinth_token
    uploadFile = jar
    versionNumber = mod_version
    versionType = 'alpha'
    dependencies {
        required.version 'the-impossible-library', til_version
    }
}

wiki {
    wikiAccessToken = wiki_token.toString()
    docs {
        musictriggers {
            root = file "docs/$mod_id"
        }
    }
}