/**
 * Build workflow guidelines
 * api -> (fabric, forge, legacy, neoforge) -> (1.12, 1.16, 1.18, 1.19, 1.20, 1.21) -> (minor versions) -> main
 * Shading and relocation must happen within each module to properly respect reobfuscation.
 * Any necessary reobfuscations must happen in the version the deobfuscations happened in.
 */
buildscript {
    repositories {
        gradlePluginPortal() {
            content {
                plugin_portal_content_short.split(';').each {grp ->
                    includeGroup grp
                }
            }
        }
    }
    dependencies {
        classpath "$wiki_plugin:$wiki_version"
    }
}

apply from: rootProject.file('gradle\\java23.gradle')
plugins.apply 'org.moddedmc.wiki.toolkit'

//noinspection GroovyUnusedAssignment
def base = project ':api'
def legacy_1_12_2 = project ':legacy:1.12'

jar {
    legacy_1_12_2.afterEvaluate { from(it.shadowJar.archiveFile.collect { zipTree it }) }
    manifest {
        def versionStr = project.version.toString()
        def manifest_version = versionStr.contains('+') ?
                versionStr.substring(0,versionStr.indexOf('+')) : versionStr
        attributes([
                'Implementation-Title': project.name,
                'Implementation-Version': manifest_version,
                'TILMultiversionCoreMods': coremod_entrypoint,
                'TILMultiversionMods': mod_entrypoint
        ])
    }
}

[ ':legacy:1.12:build' ].forEach { tasks.jar.mustRunAfter it }

wiki {
    wikiAccessToken = wiki_token
    docs {
        mod_id {
            root = file "docs/$mod_id"
        }
    }
}