# Gradle Args
org.gradle.caching=true
org.gradle.daemon=false
org.gradle.jvm.version=23
org.gradle.jvmargs=-Xms2G -Xmx4G
org.gradle.logging.level=lifecycle
org.gradle.parallel=true

# Universal Packages
base_package=mods.thecomputerizer.musictriggers
shadow_package=mods.thecomputerizer.shadow

# Universal Mod Constants
coremod_entrypoint=mods.thecomputerizer.musictriggers.api.core.MTCoreEntryPoint
mod_authors=The_Computerizer
mod_description=Play music and sounds based on in-game triggers
mod_entrypoint=mods.thecomputerizer.musictriggers.api.common.MTCommonEntryPoint
mod_id=musictriggers
mod_license=LGPL V3.0
mod_mixin=mixins.musictriggers.json
mod_name=Music Triggers
mod_refmap=musictriggers.refmap.json
mod_version=7.0.2

# Universal Constants
fabric_api_artifact=net.fabricmc.fabric-api:fabric-api
fabric_loader_artifact=net.fabricmc:fabric-loader
fabric_mc=com.mojang:minecraft
fancygradle_plugin=wtf.gofancy.fancygradle:wtf.gofancy.fancygradle.gradle.plugin
fancygradle_version=1.+
foojay_plugin=org.gradle.toolchains.foojay-resolver-convention:org.gradle.toolchains.foojay-resolver-convention.gradle.plugin
foojay_version=0.+
forge_mc=net.minecraftforge:forge
forgegradle_plugin=net.minecraftforge.gradle:net.minecraftforge.gradle.gradle.plugin
forgegradle_version=6.+
loom_plugin=fabric-loom:fabric-loom.gradle.plugin
loom_version=1.9.+
mixingradle_plugin=org.spongepowered:mixingradle
mixingradle_version=0.+
modrinth_plugin=com.modrinth.minotaur:com.modrinth.minotaur.gradle.plugin
modrinth_version=2.+
parchment_data=org.parchmentmc.data:parchment
parchment_forge_plugin=org.parchmentmc.librarian.forgegradle:org.parchmentmc.librarian.forgegradle.gradle.plugin
parchment_forge_version=1.+
shadow_plugin=com.gradleup.shadow:shadow-gradle-plugin
shadow_version=9.+
til_artifact=mods.thecomputerizer.theimpossiblelibrary:theimpossiblelibrary
wiki_plugin=org.moddedmc.wiki.toolkit:org.moddedmc.wiki.toolkit.gradle.plugin
wiki_version=0.+

# Universal Dependencies
asm_version=9.7
cloning_version=1.10.3
harder_version=2.3.9
httpclient_version=4.5.14
httpcore_version=4.4.16
ibxm_version=a75
jaadec_version=0.1.3
jackson_version=2.9.10
joml_version=1.10.5
json_version=20220924
jsoup_version=1.12.1
lava_dsp_version=0.+
lava_dspx_version=2.+
lava_natives_version=2.+
lava_version=1.+
mixin_version=0.8.5
nanojson_version=1.7
native_loader_version=0.+
rhino_version=1.7.14
slf4j_version=1.7.30
til_version=0.4.2
toml4j_version=0.7.2
youtube_source_version=1.12.0

######################### VERSIONS #########################

# Minecraft Versions
minecraft_1_12_2=1.12.2
minecraft_1_16=1.16
minecraft_1_16_5=1.16.5
minecraft_1_18=1.18
minecraft_1_18_2=1.18.2
minecraft_1_19=1.19
minecraft_1_19_2=1.19.2
minecraft_1_19_4=1.19.4
minecraft_1_20=1.20
minecraft_1_20_1=1.20.1
minecraft_1_20_4=1.20.4
minecraft_1_20_6=1.20.6
minecraft_1_21=1.21
minecraft_1_21_1=1.21.1

# Legacy Mappings Versions
legacy_mappings_1_12_2=39-1.12

# Parchment Versions
parchment_1_16_5=2022.03.06
parchment_1_18_2=2022.11.06
parchment_1_19_2=2022.11.27
parchment_1_19_4=2023.06.26
parchment_1_20_1=2023.09.03
parchment_1_20_4=2024.04.14
parchment_1_20_6=2024.06.16
parchment_1_21_1=2024.11.17

# Fabric Versions
fabric_loader=0.+
fabric_1_16_5=0.42.0+1.16
fabric_1_18_2=0.77.0+1.18.2
fabric_1_19_2=0.77.0+1.19.2
fabric_1_19_4=0.87.2+1.19.4
fabric_1_20_1=0.92.2+1.20.1
fabric_1_20_4=0.97.2+1.20.4
fabric_1_20_6=0.100.4+1.20.6
fabric_1_21_1=0.105.0+1.21.1

# Forge Versions
forge_1_12_2=1.12.2-14.23.5.2860
forge_1_16_5=1.16.5-36.2.42
forge_1_18_2=1.18.2-40.3.6
forge_1_19_2=1.19.2-43.4.20
forge_1_19_4=1.19.4-45.3.24
forge_1_20_1=1.20.1-47.3.33
forge_1_20_4=1.20.4-49.1.37
forge_1_20_6=1.20.6-50.1.48
forge_1_21_1=1.21.1-52.0.53

# NeoForge Versions
neoforge_1_20_1=1.20.1
neoforge_1_20_4=1.20.4
neoforge_1_20_6=1.20.6
neoforge_1_21_1=1.21.1

######################### MODRINTH DEPENDENCIES #########################

# Cloth Config
cloth_artifact=maven.modrinth:cloth-config
cloth_1_16_5=4.17.101
cloth_1_18_2=6.5.102
cloth_1_19_2=8.3.134+fabric
cloth_1_19_4=10.1.135+fabric
cloth_1_20_1=11.1.136+fabric
cloth_1_20_4=13.0.138+fabric
cloth_1_20_6=14.0.139+fabric
cloth_1_21_1=15.0.140+fabric

# Mod Menu
modmenu_artifact=maven.modrinth:modmenu
modmenu_1_16_5=1.16.23
modmenu_1_18_2=3.2.5
modmenu_1_19_2=4.2.0-beta.2
modmenu_1_19_4=6.3.1
modmenu_1_20_1=7.2.2
modmenu_1_20_4=9.2.0
modmenu_1_20_6=10.0.0
modmenu_1_21_1=11.0.2

######################### CURSEFORGE DEPENDENCIES #########################

# Configured
configured_artifact=curse.maven:configured-457570
configured_1_16_5=4462830
configured_1_18_2=4462832
configured_1_19_2=4462837
configured_1_19_4=4462894
configured_fabric_1_20_1=5180902
configured_forge_1_20_1=5180900
configured_fabric_1_20_4=5105023
configured_forge_1_20_4=5105022
configured_neoforge_1_20_4=5105024
configured_fabric_1_20_6=5340195
configured_forge_1_20_6=5340193
configured_neoforge_1_20_6=5340194
configured_fabric_1_21=5441234
configured_forge_1_21=5441231
configured_neoforge_1_21=5441232

# Serene Seasons
serene_seasons_artifact=curse.maven:sereneseasons-291874
serene_seasons_1_12_2=2799213
serene_seasons_1_16_5=4537666
serene_seasons_1_18_2=3804257
serene_seasons_1_19_2=4037228
serene_seasons_1_19_4=4577599
serene_seasons_fabric_1_20_1=5790654
serene_seasons_forge_1_20_1=5790653
serene_seasons_fabric_1_20_4=5206535
serene_seasons_forge_1_20_4=5206531
serene_seasons_neoforge_1_20_4=5206533
serene_seasons_fabric_1_20_6=5420643
serene_seasons_forge_1_20_6=5420642
serene_seasons_neoforge_1_20_6=5420644
serene_seasons_fabric_1_21_1=5753502
serene_seasons_forge_1_21_1=5753500
serene_seasons_neoforge_1_21_1=5753503

######################### OTHER DEPENDENCIES #########################

# JEI
jei_artifact=mezz.jei
jei_1_12_2=jei_1.12.2:4.16.1.1012
jei_1_16_5=jei-1.16.5:7.8.0.1012
jei_fabric_1_18_2=jei-1.18.2-fabric:10.2.1.1008
jei_forge_1_18_2=jei-1.18.2-forge:10.2.1.1008
jei_fabric_1_19_2=jei-1.19.2-fabric:11.8.1.1033
jei_forge_1_19_2=jei-1.19.2-forge:11.8.1.1033
jei_fabric_1_19_4=jei-1.19.4-fabric:13.1.0.18
jei_forge_1_19_4=jei-1.19.4-forge:13.1.0.18
jei_fabric_1_20_1=jei-1.20.1-fabric:15.20.0.104
jei_forge_1_20_1=jei-1.20.1-forge:15.20.0.104
jei_fabric_1_20_4=jei-1.20.4-fabric:17.3.1.4
jei_forge_1_20_4=jei-1.20.4-forge:17.3.1.4
jei_neoforge_1_20_4=jei-1.20.4-neoforge:17.3.1.4
jei_fabric_1_20_6=jei-1.20.6-fabric:18.0.0.65
jei_forge_1_20_6=jei-1.20.6-forge:18.0.0.65
jei_neoforge_1_20_6=jei-1.20.6-neoforge:18.0.0.65
jei_fabric_1_21_1=jei-1.21.1-fabric:19.21.0.246
jei_forge_1_21_1=jei-1.21.1-forge:19.21.0.246
jei_neoforge_1_21_1=jei-1.21.1-neoforge:19.21.0.246

############################## CONTENT & OTHER ##############################

fabric_content=fabric-loom;net.fabricmc;net.fabricmc.fabric-api
forge_content=net.minecraftforge;net.minecraftforge.gradle;org.spongepowered
neoforge_content=net.minecraftforge;net.neoforged;net.neoforged.gradle;net.neoforged.gradle.userdev
parchment_content=org.parchmentmc;org.parchmentmc.data;org.parchmentmc.feather;org.parchmentmc.librarian.forgegradle
plugin_portal_content=com.beust;com.fasterxml;com.fasterxml.jackson;com.fasterxml.jackson.core;\
  com.fasterxml.jackson.dataformat;com.fasterxml.woodstox;com.github.javaparser;com.google.code.findbugs;\
  com.google.code.gson;com.google.errorprone;com.google.guava;com.google.j2objc;com.gradleup.shadow;\
  com.machinezoo.noexception;com.thoughtworks.qdox;commons-codec;commons-io;commons-logging;de.siegmar;\
  gradle.plugin.org.jetbrains.gradle.plugin.idea-ext;info.picocli;io.codechicken;io.fabric8;\
  io.netty;it.unimi.dsi;jakarta.platform;jline;me.jamiemansfield;net.covers1624;net.sf.jopt-simple;org.apache;\
  org.apache.ant;org.apache.commons;org.apache.groovy;org.apache.httpcomponents;org.apache.ivy;org.apache.logging;\
  org.apache.logging.log4j;org.apache.maven;org.benf;org.cadixdev;org.checkerframework;org.codehaus;\
  org.codehaus.groovy;org.codehaus.plexus;org.codehaus.woodstox;org.eclipse.ee4j;org.eclipse.jdt;org.eclipse.jetty;\
  org.gradle.toolchains;org.gradle.toolchains.foojay-resolver-convention;org.jdom;org.jetbrains;org.jetbrains.kotlin;\
  org.jetbrains.kotlinx;org.junit;org.junit.jupiter;org.junit.platform;org.mockito;org.ow2;org.ow2.asm;org.slf4j;\
  org.sonatype.oss;org.springframework;org.opentest4j;org.testng;org.tukaani;org.vafer;org.webjars;org.zeroturnaround
plugin_portal_content_short=com.modrinth.minotaur;com.google.code.gson;com.squareup.okhttp3;com.squareup.okio;\
  commons-codec;com.googlecode.javaewah;dev.masecla;org.apache;org.apache.commons;org.eclipse.jgit;\
  org.jetbrains;org.jetbrains.kotlin;org.junit;org.moddedmc.wiki;org.moddedmc.wiki.toolkit;org.ow2;org.ow2.asm;\
  org.slf4j;org.sonatype.oss;org.zeroturnaround
relocate_these=certificates,com.fasterxml.jackson,com.grack.nanojson,com.sedmelluq.discord.lavaplayer.container,\
  com.sedmelluq.discord.lavaplayer.filter,com.sedmelluq.discord.lavaplayer.format,\
  com.sedmelluq.discord.lavaplayer.player,com.sedmelluq.discord.lavaplayer.remote,\
  com.sedmelluq.discord.lavaplayer.source,com.sedmelluq.discord.lavaplayer.tools,\
  com.sedmelluq.discord.lavaplayer.track,com.sedmelluq.lava.common.tools,com.sedmelluq.lava.extensions,\
  com.sedmelluq.lava.player,com.sedmelluq.lavaplayer.extensions,com.rits.cloning,com.rits.perspectives,\
  dev.lavalink.youtube,ibxm,mozilla,net.iharder,net.sourceforge.jaad.aac,org.apache.http,org.json,org.jsoup,\
  org.mozilla.classfile,org.slf4j
settings_plugin_content=com.google.code.gson;com.gradle;org.gradle.toolchains;\
  org.gradle.toolchains.foojay-resolver-convention