############################ ARGS ############################

# Gradle Args
org.gradle.jvmargs=-Xms1G -Xmx2G
# Other Args
common_entrypoint_arg=-Dtil.classpath.mods=mods.thecomputerizer.theimpossiblelibrary.api.common.TILCommonEntryPoint;\
  mods.thecomputerizer.musictriggers.api.common.MTCommonEntryPoint
core_entrypoint_arg=-Dtil.classpath.coremods=mods.thecomputerizer.theimpossiblelibrary.api.core.TILCoreEntryPoint;\
  mods.thecomputerizer.musictriggers.api.core.MTCoreEntryPoint
dev_arg=-Dtil.dev=true

######################### UNIVERSALS #########################

# Packages
base_package=mods.thecomputerizer.musictriggers
shadow_package=mods.thecomputerizer.shadow

# Mod Constants
coremod_entrypoint=mods.thecomputerizer.musictriggers.api.core.MTCoreEntryPoint
mod_authors=The_Computerizer
mod_description=Play music and sounds based on in-game triggers
mod_entrypoint=mods.thecomputerizer.musictriggers.api.common.MTCommonEntryPoint
mod_id=musictriggers
mod_license=LGPL V3.0
mod_mixin=mixins.musictriggers.json
mod_name=Music Triggers
mod_refmap=musictriggers.refmap.json
mod_version=7.0.4

# Dependency Groups, Names, & Plugins
asm_commons_artifact=org.ow2.asm:asm-commons
asm_util_artifact=org.ow2.asm:asm-util
bnd_artifact=biz.aQute.bnd:annotation
commons_io_artifact=commons-io:commons-io
commons_lang3_artifact=org.apache.commons:commons-lang3
fancygradle_plugin=wtf.gofancy.fancygradle:wtf.gofancy.fancygradle.gradle.plugin
fastutil_artifact=it.unimi.dsi:fastutil
foojay_plugin=org.gradle.toolchains.foojay-resolver-convention:org.gradle.toolchains.foojay-resolver-convention.gradle.plugin
forge_mc=net.minecraftforge:forge
forgegradle_plugin=net.minecraftforge.gradle:net.minecraftforge.gradle.gradle.plugin
jsr_artifact=com.google.code.findbugs:jsr305
log4j_artifact=org.apache.logging.log4j:log4j-core
modrinth_plugin=com.modrinth.minotaur:com.modrinth.minotaur.gradle.plugin
netty_artifact=io.netty:netty-all
shadow_plugin=com.gradleup.shadow:shadow-gradle-plugin
til_artifact=mods.thecomputerizer.theimpossiblelibrary:theimpossiblelibrary
wiki_plugin=org.moddedmc.wiki.toolkit:org.moddedmc.wiki.toolkit.gradle.plugin

# Dependency Versions
asm_version=+
bnd_version=2.+
cloning_version=+
commons_io_version=2.+
commons_lang3_version=3.+
fancygradle_version=+
fastutil_version=7.+
foojay_version=+
forgegradle_version=+
harder_version=+
httpclient_version=4.+
httpcore_version=4.+
ibxm_version=a75
jaadec_version=0.+
jackson_version=2.18.+
json_version=+
jsoup_version=+
jsr_version=3.+
lava_dsp_version=0.+
lava_dspx_version=2.+
lava_natives_version=2.+
lava_version=1.+
log4j_version=2.+
modrinth_version=+
nanojson_version=+
native_loader_version=0.+
netty_version=4.1.+
rhino_version=1.7.+
slf4j_version=+
shadow_version=+
til_version=0.4.4
wiki_version=+
youtube_source_version=1.+

######################### VERSIONS & DEPENDENCIES #########################

# 1.12.2 Dependency Groups, Name, & Plugins
assetmover_artifact=com.cleanroommc:assetmover
cleanroom_mixin_artifact=com.cleanroommc:sponge-mixin
gson_artifact=com.google.code.gson:gson
guava_artifact=com.google.guava:guava
jline_group=org.jline
lwjglx_artifact=com.cleanroommc:lwjglx
runtime_mods_1_12_2=bookshelf;champions;coroutil;dsurround;dsurround_lib;gamestages;hei;infernal_mobs;nyx;resloader;\
  seasons;top;weather2
unimined_plugin=xyz.wagyourtail.unimined:xyz.wagyourtail.unimined.gradle.plugin

# 1.12.2 Dependency Versions
assetmover_version=2.+
cleanroom_loader_version=0.3.0-alpha
cleanroom_mixin_version=0.+
gson_annotation=2.8.+
guava_annotation=32.1.+
lwjglx_version=1.+
unimined_version=1.+

# 1.12.2 Dependency Forced Versions
jline_forced=3.25.1

# AtomicStryker's Infernal Mobs
infernal_mobs_artifact=curse.maven:infernal-mobs-227875
infernal_mobs_1_12_2=3431758

# Bookshelf
bookshelf_artifact=net.darkhax.bookshelf:Bookshelf
bookshelf_1_12_2=1.12.2:2.3.590

# Champions
champions_artifact=curse.maven:champions-307152
champions_1_12_2=3177947

# CoroUtil
coroutil_artifact=curse.maven:coroutil-237749
coroutil_1_12_2=2902920

# Dynamic Surroundings
dsurround_artifact=curse.maven:dsurround-238891
dsurround_1_12_2=3497269

# Forge Versions
forge_1_12_2=1.12.2-14.23.5.2860

# Game Stages
gamestages_artifact=net.darkhax.gamestages:GameStages
gamestages_1_12_2=1.12.2:2.0.99

# Had Enough Items
hei_artifact=curse.maven:hei-557549
hei_1_12_2=6187146

# Legacy Mappings Versions
legacy_mappings_1_12_2=39-1.12

# Minecraft Versions
minecraft_1_12_2=1.12.2
supported_versions=12.2;16.5;18.2;19.2;19.4;20.1;20.4;20.6;21.1

# Nyx
nyx_artifact=curse.maven:nyx-349214
nyx_1_12_2=3161738

# Ore Lib (Library for Dynamic Surroundings)
dsurround_lib_artifact=curse.maven:dsurround-lib-307806
dsurround_lib_1_12_2=2820815

# Resource Loader
resloader_artifact=curse.maven:resource-loader-303876
resloader_1_12_2=2623013

# Serene Seasons
seasons_artifact=curse.maven:sereneseasons-291874
seasons_1_12_2=2799213

# The One Probe
top_artifact=curse.maven:top-245211
top_1_12_2=2667280

# Weather 2 - Remastered
weather2_artifact=curse.maven:weather2-remastered-695602
weather2_1_12_2=5705205

############################## CONTENT & OTHER ##############################

plugin_portal_content_short=com.modrinth.minotaur;com.google.code.gson;com.squareup.okhttp3;com.squareup.okio;\
  commons-codec;com.googlecode.javaewah;dev.masecla;org.apache;org.apache.commons;org.eclipse.jgit;\
  org.jetbrains;org.jetbrains.kotlin;org.junit;org.moddedmc.wiki;org.moddedmc.wiki.toolkit;org.ow2;org.ow2.asm;\
  org.slf4j;org.sonatype.oss;org.zeroturnaround
relocate_these=certificates,com.fasterxml.jackson,com.grack.nanojson,com.sedmelluq.discord.lavaplayer.container,\
  com.sedmelluq.discord.lavaplayer.filter,com.sedmelluq.discord.lavaplayer.format,\
  com.sedmelluq.discord.lavaplayer.player,com.sedmelluq.discord.lavaplayer.remote,\
  com.sedmelluq.discord.lavaplayer.source,com.sedmelluq.discord.lavaplayer.tools,\
  com.sedmelluq.discord.lavaplayer.track,com.sedmelluq.lava.common.tools,com.sedmelluq.lava.extensions,\
  com.sedmelluq.lava.player,com.sedmelluq.lavaplayer.extensions,com.rits.cloning,com.rits.perspectives,\
  dev.lavalink.youtube,ibxm,mozilla,net.iharder,net.sourceforge.jaad.aac,org.apache.http,org.json,org.jsoup,\
  org.mozilla.classfile,org.slf4j
settings_plugin_content=com.google.code.gson;com.gradle;org.gradle.toolchains;\
  org.gradle.toolchains.foojay-resolver-convention

unimined_plugin_portal=at.favre.lib;\
  com.fasterxml;\
  com.fasterxml.jackson;\
  com.fasterxml.woodstox;\
  com.github.hypfvieh;\
  com.github.javakeyring;\
  com.github.jnr;\
  com.github.jponge;\
  com.google.code.findbugs;\
  com.google.code.gson;\
  com.google.errorprone;\
  com.google.guava;\
  com.google.j2objc;\
  com.gradleup.shadow;\
  com.googlecode.javaewah;\
  com.nothome;\
  com.salesforce.maven;\
  com.squareup.okio;\
  com.sschr15.annotations;\
  commons-codec;\
  commons-io;\
  de.swiesend;\
  io.github.oshai;\
  io.jsonwebtoken;\
  io.sigpipe;\
  jakarta.platform;\
  net.java.dev.jna;\
  net.lenni0451.commons;\
  net.raphimc;\
  net.sf.jopt-simple;\
  org.apache;\
  org.apache.ant;\
  org.apache.commons;\
  org.apache.groovy;\
  org.apache.logging;\
  org.apache.logging.log4j;\
  org.apache.maven;\
  org.checkerframework;\
  org.codehaus.plexus;\
  org.codehaus.woodstox;\
  org.eclipse.ee4j;\
  org.eclipse.jgit;\
  org.jdom;\
  org.jetbrains;\
  org.jetbrains.kotlin;\
  org.jetbrains.kotlinx;\
  org.junit;\
  org.mockito;\
  org.ow2;\
  org.ow2.asm;\
  org.slf4j;\
  org.sonatype.oss;\
  org.springframework;\
  org.vafer;\
  pt.davidafsilva.apple;\
  trove
unimined_releases=net.fabricmc;net.minecraftforge;net.neoforged;xyz.wagyourtail.commons;xyz.wagyourtail.unimined.mapping
unimined_snapshots=xyz.wagyourtail.commons;xyz.wagyourtail.unimined;xyz.wagyourtail.unimined.mapping