pluginManagement {
    repositories {
        gradlePluginPortal() {
            content {
                settings_plugin_content.split(';').each {grp ->
                    includeGroup grp
                }
            }
        }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '+'
}

rootProject.name = 'Music-Triggers'

def paths = [ ':api', ':legacy:cleanroom' ]

paths.forEach {
    include it
}

paths.forEach {
    String[] split = (it.startsWith(':') ? it.substring(1) : it).split(':')
    findProject(it)?.name = split.length>1 ? split.last() : split.first()
}