pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            name = 'Fabric'
            url = uri('https://maven.fabricmc.net/')
            content {
                [ 'fabric-loom', 'net.fabricmc', 'net.fabricmc.fabric-api' ].forEach { includeGroup it }
            }
        }
        maven {
            name = 'Forge'
            url = uri('https://maven.minecraftforge.net/')
            content {
                [ 'net.minecraftforge', 'net.minecraftforge.gradle',
                  'org.spongepowered' ].forEach{ includeGroup it }
            }
        }
        maven {
            name = 'Garden of Fancy'
            url = uri('https://maven.gofancy.wtf/releases')
            content {
                includeGroup 'wtf.gofancy.fancygradle'
            }
        }
        maven {
            name = 'ParchmentMC'
            url = uri('https://maven.parchmentmc.org')
            content {
                [ 'org.parchmentmc', 'org.parchmentmc.feather',
                  'org.parchmentmc.librarian.forgegradle' ].forEach { includeGroup it }
            }
        }
    }
    includeBuild("${default_directory}\\Multiversion-Project-Helper")
}

plugins {
    id 'multiversionhelper.settings'
}

rootProject.name = 'Music-Triggers'

multiversion {
    name = 'Music-Triggers'
    group = base_package
    default_classes = [ 'client', 'common' ]
    default_preprocessor = 'gradle\\\\\\\\lavaplayer'
    default_resource_output = 'run_client\\\\\\\\MTResources'
    defineProject settings, 'api'
    defineVersion settings, 'legacy', '12'
    defineVersions settings, 'shared', '16', '18'
    defineVersions settings, 'forge', '16', '18'
    defineVersions settings, 'fabric', '16', '18'
}