pluginManagement {
    repositories {
        gradlePluginPortal() {
            content {
                plugin_portal_content.split(';').each {grp ->
                    includeGroup grp
                }
            }
        }
        maven {
            name = 'Fabric'
            url = uri 'https://maven.fabricmc.net/'
            content {
                fabric_content.split(';').each {grp ->
                    includeGroup grp
                }
            }
        }
        maven {
            name = 'Forge'
            url = uri 'https://maven.minecraftforge.net/'
            content {
                forge_content.split(';').each {grp ->
                    includeGroup grp
                }
            }
        }
        maven {
            name = 'Garden of Fancy'
            url = uri 'https://maven.gofancy.wtf/releases'
            content {
                includeGroup 'wtf.gofancy.fancygradle'
            }
        }
        maven {
            name = 'ParchmentMC'
            url = uri 'https://maven.parchmentmc.org'
            content {
                parchment_content.split(';').each {grp ->
                    includeGroup grp
                }
            }
        }
    }
    includeBuild("${default_directory}\\Multiversion-Project-Helper")
}

plugins {
    id 'multiversionhelper.settings'
}

rootProject.name = 'Music-Triggers'

multiversion {
    name = 'Music-Triggers'
    group = base_package
    default_classes = [ 'client', 'common' ]
    default_preprocessor = 'gradle\\\\\\\\lavaplayer'
    default_resource_output = 'run_client\\\\\\\\MTResources'
}

def paths = [                                ':api',     ':legacy:1.12',
  ':fabric:1.16',        ':forge:1.16',                                                        ':shared:1.16',
  ':fabric:1.18',        ':forge:1.18',                                                        ':shared:1.18',
                         ':forge:1.19',                                                        ':shared:1.19',
                         ':forge:1.20',                                                        ':shared:1.20',
                         ':forge:1.21',                                                        ':shared:1.21',
                         ':forge:1.19:1.19.2',                                          ':shared:1.19:1.19.2',
                         ':forge:1.19:1.19.4',                                          ':shared:1.19:1.19.4',
                         ':forge:1.20:1.20.1',                                          ':shared:1.20:1.20.1',
                         ':forge:1.20:1.20.4',                                          ':shared:1.20:1.20.4',
                         ':forge:1.20:1.20.6',                                          ':shared:1.20:1.20.6',
                         ':forge:1.21:1.21.1',                                          ':shared:1.21:1.21.1'
]

paths.forEach {
    include it
}

paths.forEach {
    String[] split = (it.startsWith(':') ? it.substring(1) : it).split(':')
    String name = split.first()
    if(split.length>1) {
        String last = split.last()
        if(name=='api' || name=='legacy') name = last
        else name = name+"_"+last
    }
    findProject(it)?.name = name
}