/**
 * Shared implementations for anything based in 1.16. Compiles against Forge
 */
buildscript {
    repositories {
        gradlePluginPortal() {
            content {
                plugin_portal_content.split(';').each {grp ->
                    includeGroup grp
                }
            }
        }
        maven {
            name = 'Forge'
            url = uri 'https://maven.minecraftforge.net/'
            content {
                forge_content.split(';').each {grp ->
                    includeGroup grp
                }
            }
        }
        maven {
            name = 'ParchmentMC'
            url = uri 'https://maven.parchmentmc.org'
            content {
                parchment_content.split(';').each {grp ->
                    includeGroup grp
                }
            }
        }
    }
    dependencies {
        classpath "$forgegradle_plugin:$forgegradle_version"
        classpath "$parchment_forge_plugin:$parchment_forge_version"
    }
}

apply from: rootProject.file('gradle\\java8-module.gradle')
apply from: rootProject.file('gradle\\til-compile.gradle')

plugins.apply 'net.minecraftforge.gradle'
plugins.apply 'org.parchmentmc.librarian.forgegradle'

minecraft {
    mappings channel: 'parchment', version: "${parchment_version}-${minecraft_version}"
    runs {
        def args = [ '-Dtil.dev=true' ]
        configureEach {
            def srgToMcpFile = project.tasks.createSrgToMcp.outputs.files[0].path
            property 'net.minecraftforge.gradle.GradleStart.srg.srg-mcp', srgToMcpFile
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', srgToMcpFile
        }

        client {
            workingDirectory file('run_client')
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'trace'
            jvmArgs args
        }
        server {
            workingDirectory file('run_server')
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'
            jvmArgs args
        }
    }
}

def base = project ':api'
def shared = project ':shared'

dependencies {
    //noinspection VulnerableLibrariesLocal
    minecraft "$forge_mc:$minecraft_version-$forge_version"
    api base
    api shared
}

processResources {
    from shared.processResources.outputs
}

processTestResources {
    from shared.processTestResources.outputs
}

jar {
    manifest {
        attributes([
                'Implementation-Title': name,
                'Implementation-Version': version
        ])
    }
}

tasks.jar.dependsOn ':shared:build'