plugins.apply 'mods.thecomputerizer.plugin.forge'

multiversion {
    api = [ 'api', 'forge:forge_1.19', 'shared:shared_1.19:shared_1.19.2' ]
    entrypoint = mod_entrypoint
    local_lib = true
    parent = 'forge:forge_1.19'
    preprocessor = 'gradle\\lavaplayer'
    resource_output = 'run_client\\MTResources'
    setVersions 19, 2
    shadow_relocations = [ shadow_package: relocate_these.split(',').toList()]
    onEvaluateFinished project
}