plugins.apply 'mods.thecomputerizer.plugin.forge'

multiversion {
    api = [ 'api', 'forge:forge_1.20', 'shared:shared_1.20:shared_1.20.4' ]
    entrypoint = mod_entrypoint
    local_lib = true
    parent = 'forge:forge_1.20'
    preprocessor = 'gradle\\lavaplayer'
    resource_output = 'run_client\\MTResources'
    setVersions 20, 4
    shadow_relocations = [ shadow_package: relocate_these.split(',').toList()]
    onEvaluateFinished project
}