plugins.apply 'mods.thecomputerizer.plugin.forge'

multiversion {
    api = [ 'api', 'forge', 'shared:shared_1.16' ]
    entrypoint = mod_entrypoint
    local_lib = true
    parent = 'forge'
    preprocessor = 'gradle\\lavaplayer'
    resource_output = 'run_client\\MTResources'
    setVersions 16
    shadow_relocations = [ "$shadow_package": relocate_these.split(',').toList()]
    onEvaluateFinished project
}

dependencies {
    //mod support dependencies
    runtimeOnly fg.deobf("curse.maven:betterweather-400714:${betterweather_version}")
    runtimeOnly fg.deobf("curse.maven:blueskies-312918:${blueskies_version}")
    runtimeOnly fg.deobf("curse.maven:champions-307152:${champions_version}")
    runtimeOnly fg.deobf("curse.maven:configured-457570:${configured_version}")
    runtimeOnly fg.deobf("curse.maven:dsurround-238891:${dsurround_version}")
    runtimeOnly fg.deobf("curse.maven:enhancedcelestials-438447:${enhancedcelestials_version}")
    runtimeOnly fg.deobf("curse.maven:sereneseasons-291874:${seasons_version}")
    runtimeOnly fg.deobf("curse.maven:structure-gel-378802:${structuregel_version}")
    runtimeOnly fg.deobf("mezz.jei:jei-${minecraft_version}:${jei_version}")
    runtimeOnly fg.deobf("net.darkhax.bookshelf:Bookshelf-${minecraft_version}:${bookshelf_version}")
    runtimeOnly fg.deobf("net.darkhax.gamestages:GameStages-Forge-${minecraft_version}:${gamestages_version}")
}

jar {
    manifest {
        attributes([
                'FMLAT': mod_accesstransformer,
                'Implementation-Title': project.name,
                'MixinConfigs': mod_mixin,
                'TILMultiversionMods': mod_entrypoint,
                'TweakClass': mod_tweakclass,
                'TweakOrder': 0
        ])
    }
}