repositories {
    maven {
        name = 'Modrinth'
        url = uri 'https://api.modrinth.com/maven'
        content {
            includeGroup 'maven.modrinth'
        }
    }
}

configurations {
    implementation.resolutionStrategy {

    }
}

dependencies {
    implementation "maven.modrinth:the-impossible-library:$til_version"
    //implementation "maven.modrinth:the-impossible-library:${til_version}:javadoc"
    //implementation "maven.modrinth:the-impossible-library:${til_version}:sources"
}
