//file:noinspection DependencyNotationArgument
plugins.apply 'mods.thecomputerizer.plugin.forge'

multiversion {
    api = [ 'api', 'legacy' ]
    entrypoint = mod_entrypoint
    fancy_gradle = true
    local_lib = true
    mappings_channel = 'stable'
    mixin = false
    parchment = false
    parent = 'legacy'
    preprocessor = 'gradle\\lavaplayer'
    resource_output = 'run_client\\MTResources'
    setVersions 12
    shadow_relocations = [ "$shadow_package": relocate_these.split(',').toList() ]
    onEvaluateFinished project
}

dependencies {
    //mod support & utility
    runtimeOnly "$bookshelf_artifact-$bookshelf_1_12_2"
    runtimeOnly "$champions_artifact:$champions_1_12_2"
    runtimeOnly "$coroutil_artifact:$coroutil_1_12_2"
    runtimeOnly "$dsurround_artifact:$dsurround_1_12_2"
    runtimeOnly "$dsurround_lib_artifact:$dsurround_lib_1_12_2"
    runtimeOnly "$gamestages_artifact-$gamestages_1_12_2"
    runtimeOnly "$hei_artifact:$hei_1_12_2"
    runtimeOnly "$infernal_mobs_artifact:$infernal_mobs_1_12_2"
    runtimeOnly "$nyx_artifact:$nyx_1_12_2"
    runtimeOnly "$resloader_artifact:$resloader_1_12_2"
    runtimeOnly "$seasons_artifact:$seasons_1_12_2"
    runtimeOnly "$top_artifact:$top_1_12_2"
    runtimeOnly "$weather2_artifact:$weather2_1_12_2"
}

jar {
    manifest {
        attributes([
                'Implementation-Title': project.name,
                'TILMultiversionMods': mod_entrypoint
        ])
    }
}

tasks.withType(JavaExec).configureEach {
    dependsOn shadowJar
    classpath project.configurations.runtimeClasspath, shadowJar.archiveFile.get().asFile
}