//file:noinspection DependencyNotationArgument
plugins.apply 'mods.thecomputerizer.plugin.forge'

multiversion {
    api = [ 'api', 'legacy' ]
    entrypoint = mod_entrypoint
    fancy_gradle = true
    local_lib = true
    mappings_channel = 'stable'
    mixin = false
    parchment = false
    parent = 'legacy'
    preprocessor = 'gradle\\lavaplayer'
    resource_output = 'run_client\\MTResources'
    setVersions 12
    shadow_relocations = [ "$shadow_package": relocate_these.split(',').toList()]
    onEvaluateFinished project
}

dependencies {
    //mod support & utility
    runtimeOnly fg.deobf("net.darkhax.bookshelf:Bookshelf-$minecraft_version:$bookshelf_version")
    runtimeOnly fg.deobf("curse.maven:champions-307152:$champions_version")
    runtimeOnly fg.deobf("curse.maven:coroutil-237749:$coroutil_version")
    runtimeOnly fg.deobf("net.darkhax.gamestages:GameStages-$minecraft_version:$gamestages_version")
    runtimeOnly fg.deobf("curse.maven:hei-557549:$hei_version")
    runtimeOnly fg.deobf("curse.maven:infernalmobs-227875:$infernal_version")
    runtimeOnly fg.deobf("curse.maven:nyx-349214:$nyx_version")
    runtimeOnly fg.deobf("curse.maven:resourcereloader-303876:$reloader_version")
    runtimeOnly fg.deobf("curse.maven:sereneseasons-291874:$seasons_version")
    runtimeOnly fg.deobf("curse.maven:top-245211:$top_version")
    //runtimeOnly fg.deobf("curse.maven:weather2-695602:$weather_version")
}

jar {
    manifest {
        attributes([
                'FMLAT': mod_accesstransformer,
                'Implementation-Title': project.name,
                'TILMultiversionMods': mod_entrypoint
        ])
    }
}

tasks.withType(JavaExec).configureEach {
    dependsOn shadowJar
    classpath project.configurations.runtimeClasspath, shadowJar.archiveFile.get().asFile
}