//file:noinspection DependencyNotationArgument
plugins.apply 'mods.thecomputerizer.plugin.forge'

multiversion {
    api = [ 'api', 'legacy' ]
    entrypoint = mod_entrypoint
    fancy_gradle = true
    local_lib = true
    mappings_channel = 'stable'
    mixin = false
    parchment = false
    parent = 'legacy'
    preprocessor = 'gradle\\lavaplayer'
    resource_output = 'run_client\\MTResources'
    setVersions 12
    shadow_relocations = [ "$shadow_package": relocate_these.split(',').toList() ]
    onEvaluateFinished project
}

String buildModDependency(String mod) {
    String mod_dependency_group_with_name = property "${mod}_artifact"
    String mod_dependency_version = property "${mod}_1_12_2"
    String separator = 'bookshelf'==mod || 'gamestages'==mod ? '-' : ':'
    return "$mod_dependency_group_with_name$separator$mod_dependency_version"
}

dependencies {
    //mod support & utility
    runtime_mods_1_12_2.split(';').each {mod ->
        runtimeOnly buildModDependency(mod)
    }
}

jar {
    manifest {
        attributes([
                'Implementation-Title': project.name,
                'TILMultiversionMods': mod_entrypoint
        ])
    }
}

tasks.withType(JavaExec).configureEach {
    dependsOn shadowJar
    classpath project.configurations.runtimeClasspath, shadowJar.archiveFile.get().asFile
}