plugins.apply 'mods.thecomputerizer.plugin.forge'

multiversion {
    api = [ 'api', 'shared:shared_1.21' ]
    entrypoint = mod_entrypoint
    local_lib = true
    parent = 'shared:shared_1.21'
    preprocessor = 'gradle\\lavaplayer'
    resource_output = 'run_client\\MTResources'
    setVersions 21, 1
    shadow_relocations = [ shadow_package: relocate_these.split(',').toList()]
    onEvaluateFinished project
}