apply from: rootProject.file('gradle\\java8.gradle')

def base = project ':api'

jar {
    from(base.shadowJar.archiveFile.collect {
        include 'mods/**'
        zipTree it
    })
}

processResources {
    from base.processResources.outputs
}

processTestResources {
    from base.processTestResources.outputs
}

tasks.jar.dependsOn ':api:build'