plugins.apply('mods.thecomputerizer.plugin.forge')

multiversion {
    api = [ 'api', 'shared' ]
    entrypoint = mod_entrypoint
    local_lib = true
    parent = 'shared'
    preprocessor = 'gradle\\lavaplayer'
    resource_output = 'run_client\\MTResources'
    setVersions 18
    shadow_relocations = [ "$shadow_package": relocate_these.split(',').toList()]
    onEvaluateFinished project
}