plugins.apply('mods.thecomputerizer.plugin.forge')

multiversion {
    api = [ 'api', 'forge', 'shared:shared_1.18' ]
    entrypoint = mod_entrypoint
    local_lib = true
    parent = 'forge'
    preprocessor = 'gradle\\lavaplayer'
    resource_output = 'run_client\\MTResources'
    setVersions 18
    shadow_relocations = [ "$shadow_package": relocate_these.split(',').toList()]
    onEvaluateFinished project
}

jar {
    manifest {
        attributes([
                'FMLAT': mod_accesstransformer,
                'Implementation-Title': project.name,
                'MixinConfigs': mod_mixin,
                'TILMultiversionMods': mod_entrypoint,
                'TweakClass': mod_tweakclass,
                'TweakOrder': 0
        ])
    }
}