plugins {
    alias libs.plugins.shadow
}

apply from: rootProject.file('gradle\\java8-module.gradle')
apply from: rootProject.file('gradle\\lavaplayer.gradle')
apply from: rootProject.file('gradle\\til-compile.gradle')

injectConstants()

repositories {
    mavenCentral()
    maven {
        name = 'SonaType'
        url = uri 'https://oss.sonatype.org/content/repositories/public/'
        content {
            includeGroup 'it.unimi.dsi'
        }
    }
}

dependencies {
    compileOnly(libs.bundles.api.compile) {
        exclude group: 'com.github.spotbugs'
    }
    compileOnly libs.spotbugs.annotations
}

processResources {
    from(sourceSets.main.resources.srcDirs)
}

def injectConstants() {
    def target = file "src/main/java/${ "${base_package}.api.MTRef".replace '.', '/'}.java"
    logger.info "Injecting constants into target file ${target.absolutePath}"
    def replacements = [ 'MODID = "': "MODID = \"$mod_id\";",
                         'NAME ="': "NAME = \"$mod_name\";",
                         'VERSION = "': "VERSION = \"$mod_version\";" ]
    List<String> lines = new ArrayList<>()
    target.eachLine { line ->
        replacements.each {entry ->
            String key = entry.key
            if(line.contains(key)) {
                int index = line.indexOf key
                line = "${line.substring(0,index)}${entry.value}"
            }
        }
        lines.add line
    }
    target.withWriter {writer ->
        lines.forEach {line ->
            writer.writeLine line
        }
    }
}

tasks.assemble.dependsOn shadowJar
tasks.jar.finalizedBy shadowJar