apply from: rootProject.file('gradle\\java8-module.gradle')
apply from: rootProject.file('gradle\\til-compile.gradle')

repositories {
    mavenCentral()
    maven {
        name = 'SonaType'
        url = uri 'https://oss.sonatype.org/content/repositories/public/'
        content {
            includeGroup 'it.unimi.dsi'
        }
    }
}

dependencies {
    compileOnly "$bnd_artifact:$bnd_version"
    compileOnly "$jsr_artifact:$jsr_version"
    compileOnly "$commons_io_artifact:$commons_io_version"
    compileOnly "$netty_artifact:$netty_version"
    compileOnly "$fastutil_artifact:$fastutil_version"
    compileOnly "$commons_lang3_artifact:$commons_lang3_version"
    compileOnly "$log4j_artifact:$log4j_version"
    compileOnly "$asm_commons_artifact:$asm_version"
    compileOnly "$asm_util_artifact:$asm_version"
}


processResources {
    from(sourceSets.main.resources.srcDirs)
}