apply from: rootProject.file('gradle\\java8-module.gradle')
apply from: rootProject.file('gradle\\til-compile.gradle')

injectConstants()

repositories {
    mavenCentral()
    maven {
        name = 'SonaType'
        url = uri 'https://oss.sonatype.org/content/repositories/public/'
        content {
            includeGroup 'it.unimi.dsi'
        }
    }
}

dependencies {
    compileOnly "$bnd_artifact:$bnd_version"
    compileOnly "$jsr_artifact:$jsr_version"
    compileOnly "$commons_io_artifact:$commons_io_version"
    compileOnly "$netty_artifact:$netty_version"
    compileOnly "$fastutil_artifact:$fastutil_version"
    compileOnly "$commons_lang3_artifact:$commons_lang3_version"
    compileOnly "$log4j_artifact:$log4j_version"
    compileOnly "$asm_commons_artifact:$asm_version"
    compileOnly "$asm_util_artifact:$asm_version"
}

processResources {
    from(sourceSets.main.resources.srcDirs)
}

def injectConstants() {
    def target = file "src/main/java/${ "${base_package}.api.MTRef".replace '.', '/'}.java"
    logger.info "Injecting constants into target file ${target.absolutePath}"
    def replacements = [ 'MODID = "': "MODID = \"$mod_id\";",
                         'NAME ="': "NAME = \"$mod_name\";",
                         'VERSION = "': "VERSION = \"$mod_version\";" ]
    List<String> lines = new ArrayList<>()
    target.eachLine { line ->
        replacements.each {entry ->
            String key = entry.key
            if(line.contains(key)) {
                int index = line.indexOf key
                line = "${line.substring(0,index)}${entry.value}"
            }
        }
        lines.add line
    }
    target.withWriter {writer ->
        lines.forEach {line ->
            writer.writeLine line
        }
    }
}